// This file is generated automatically
export const navgationHeader: string;
export const scrollBelow90Px: string;
export const header: string;
export const burger: string;
export const clicked: string;
export const innerContent: string;
export const navigation: string;
export const item: string;
export const active: string;
export const burgerClickArea: string;
export const innerContentBurger: string;
export const zIndex: string;
export const zIndexClicked: string;
export const hamburger: string;
export const burgerMenuContainer: string;
export const show: string;
export const ulMenu: string;
export const menuLink: string;
